/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jdbi

import com.opentable.db.postgres.embedded.EmbeddedPostgres
import org.jdbi.v3.core.Jdbi
import org.jdbi.v3.sqlobject.kotlin.onDemand
import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.BeforeTest
import kotlin.test.assertEquals

class LibraryTest {

    lateinit var embeddedPostgres: EmbeddedPostgres

    @BeforeTest
    fun setup() {
        embeddedPostgres = EmbeddedPostgres.start()
    }

    @Test fun testSomeLibraryMethod() {
        val user = User("Test 1", "Test 2")
        val classUnderTest = Library(embeddedPostgres.postgresDatabase)
        assertTrue(classUnderTest.save(user), "save should return 'true'")

        val jdbi = Jdbi.create(embeddedPostgres.postgresDatabase)
        jdbi.installPlugins()
        val onDemand = jdbi.onDemand<UserDao>()

        val users = onDemand.getUsers()

        assertEquals(1, users.count())
        assertEquals("Test 1", user.name)
        assertEquals("Test 2", user.lastName)
    }
}
