/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jdbi

import org.flywaydb.core.Flyway
import org.jdbi.v3.core.Jdbi
import org.jdbi.v3.sqlobject.kotlin.onDemand
import javax.sql.DataSource

class Library(private val dataSource: DataSource) {

    fun save(user: User): Boolean {

        val flyway = Flyway()
        flyway.dataSource = dataSource
        flyway.isInitOnMigrate = true
        flyway.migrate()

        val jdbi = Jdbi.create(dataSource)
        jdbi.installPlugins()
        val userDao = jdbi.onDemand<UserDao>()

        userDao.insertUser(user)

        return true
    }
}
